### PR TITLE
Implement graph functionality

### PR DESCRIPTION
**Pull request by thildahl20**

### CODE REVIEW

**Comment by mgamlem3** [comment]
@thildahl20 Do you want to go through and make these fixes so that code factor does not get angry

**Comment by mgamlem3** [comment]
Would you please edit the name to make it something useful?

**Comment by thildahl20** [comment]
I was actually just about to go do the code factor fixes. What do you mean? I think it's just a couple syntax changes for code factor, but I dont know how to change the name.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mgamlem3** [comment]
There should be an edit button at the top of the PR

- Michael Gamlem III

**Comment by thildahl20** [comment]
You mean rename the PR itself to explain how its adding graph functionality?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mgamlem3** [comment]
Yeah, that would be great.

- Michael Gamlem III

**Comment by thildahl20** [comment]
I'm going to start applying code factor fixes if you arent already doing so...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
