### PR TITLE
Update Logo and Nav Bar

### PR DESCRIPTION
**Pull request by Link196**
Convert logo to homepage link
Remove unneeded displaynav
Remove redundant homepage link on nav bar

### CODE REVIEW

**Comment by mgamlem3** [comment]
Can we also put the fix for spacing on the left side of the logo in this PR?

**Comment by Link196** [comment]
Like add more space?

**Comment by mgamlem3** [comment]
Yes, on the left side

**Comment by Link196** [comment]
I'll look into doing that.

**Pull request merged**
